name: Main

on:
  pull_request:
    types:
      - opened
      - synchronized
      - reopened
  push:
    branches:
      - main

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Download all dependencies
        run: |
          # Download all dependencies that integration tests might need later
          ./mvnw -B -V -Dstyle.color=always dependency:go-offline -f src/it/dependencies/pom.xml -P protoc-3.4.0
          ./mvnw -B -V -Dstyle.color=always dependency:go-offline -f src/it/dependencies/pom.xml -P protoc-3.11.1
          ./mvnw -B -V -Dstyle.color=always dependency:go-offline -P run-its

          # These protoc executables were downloaded in the previous phase and are being referenced in toolchains.xml
          chmod +x $HOME/.m2/repository/com/google/protobuf/protoc/3.4.0/protoc-3.4.0-linux-x86_64.exe
          chmod +x $HOME/.m2/repository/com/google/protobuf/protoc/3.11.1/protoc-3.11.1-linux-x86_64.exe

      - name: Build and test
        run: |
          ./mvnw -B -V -t .github/workflows/toolschains-linux.xml -Dstyle.color=always clean verify -P run-its -Dinvoker.streamLogs=true

